const $=s=>document.querySelector(s),C=$('#arena'),X=C.getContext('2d'),W=64,H=64,N=W*H;
const el={timer:$('#timer'),state:$('#statePill'),start:$('#startBtn'),pause:$('#pauseBtn'),reset:$('#resetBtn'),dur:$('#duration'),speed:$('#speed'),cfg:$('#teamConfig'),score:$('#scoreboard'),feed:$('#feed'),banner:$('#eventBanner'),dlg:$('#resultDialog'),title:$('#winnerTitle'),sum:$('#winnerSummary'),list:$('#resultList'),again:$('#againBtn'),close:$('#closeResultBtn')};
const COL=['#ff5b5b','#4f7cff','#25b77a','#9b6bff'],TN=['红方','蓝方','绿方','紫方'],CP=[[5,5],[58,5],[5,58],[58,58]],D=[[1,0],[-1,0],[0,1],[0,-1]];
const S={bfs:['BFS 洪流','均匀铺开边界，正面推进稳定。'],dfs:['DFS 穿刺','沿成功方向持续深入，擅长偷家。'],astar:['A* 猎手','主动追逐高价值资源节点。'],greedy:['Greedy 疯狗','只看眼前收益，爆发强但阵型容易失控。'],random:['Random 赌徒','偏随机扩张，波动最大。']};
let teams=[T(0,'bfs'),T(1,'dfs'),T(2,'astar'),T(3,'greedy')],own,ter,res,core,run=false,end=false,t=0,last=0,acc=0,dur=90,flags=new Set(),flash;
function T(id,strategy){return{id,strategy,score:0,captures:0,resources:0,territory:0,lastDir:[1,0],target:null,credit:0}}
const I=(x,y)=>y*W+x,XY=i=>[i%W,(i/W)|0],IB=(x,y)=>x>=0&&x<W&&y>=0&&y<H,RI=n=>(Math.random()*n)|0,CL=(n,a,b)=>Math.max(a,Math.min(b,n)),MD=(a,b)=>Math.abs(a[0]-b[0])+Math.abs(a[1]-b[1]);
function config(){el.cfg.innerHTML='';teams.forEach(a=>{let d=document.createElement('div');d.className='team-card';let o=Object.entries(S).map(([k,v])=>'<option value="'+k+'" '+(a.strategy===k?'selected':'')+'>'+v[0]+'</option>').join('');d.innerHTML='<div class="team-card-head"><div class="team-id"><i class="team-swatch" style="background:'+COL[a.id]+'"></i>'+TN[a.id]+'</div><span>#'+(a.id+1)+'</span></div><select data-team="'+a.id+'">'+o+'</select><div class="strategy-desc" data-desc="'+a.id+'">'+S[a.strategy][1]+'</div>';el.cfg.appendChild(d)});el.cfg.querySelectorAll('select').forEach(s=>s.onchange=e=>{let id=+e.target.dataset.team;teams[id].strategy=e.target.value;el.cfg.querySelector('[data-desc="'+id+'"]').textContent=S[e.target.value][1];if(!run)reset()})}
function reset(){run=false;end=false;t=acc=0;last=performance.now();dur=+el.dur.value;own=new Int8Array(N).fill(-1);ter=new Uint8Array(N);res=new Uint8Array(N);core=new Int8Array(N).fill(-1);flags=new Set();teams=teams.map(a=>T(a.id,a.strategy));for(let i=0;i<N;i++)ter[i]=1+(Math.random()<.17)+(Math.random()<.04);resources(24,false);seed();el.feed.innerHTML='';log('新地图生成，等待开战。');state('待机');ui();draw();el.start.textContent='开始';el.start.disabled=false;el.pause.disabled=true}
function seed(){CP.forEach(([cx,cy],id)=>{for(let y=cy-1;y<=cy+1;y++)for(let x=cx-1;x<=cx+1;x++){let i=I(x,y);own[i]=core[i]=id;ter[i]=1}});stats()}
function resources(n,center){while(n){let x=center?Math.floor(W*.28+Math.random()*W*.44):4+RI(W-8),y=center?Math.floor(H*.28+Math.random()*H*.44):4+RI(H-8),i=I(x,y);if(core[i]>=0||res[i])continue;res[i]=Math.random()<.18?3:1;n--}}
function state(s){el.state.textContent=s}function ft(s){s=Math.max(0,Math.ceil(s));return String((s/60)|0).padStart(2,'0')+':'+String(s%60).padStart(2,'0')}
function start(){if(end)reset();run=true;last=performance.now();el.start.textContent='进行中';el.start.disabled=true;el.pause.disabled=false;state('交战中');log('回合开始，四个算法同时启动。')}
function pause(){run=!run;if(run){last=performance.now();el.pause.textContent='暂停';el.start.disabled=true;state('交战中');log('模拟继续。')}else{el.pause.textContent='继续';el.start.disabled=false;el.start.textContent='继续';state('已暂停');log('模拟暂停。')}}
function loop(ts){let dt=Math.min(.1,(ts-last)/1000||0);last=ts;if(run){acc+=dt*(+el.speed.value);while(acc>=.055&&run){tick(.055);acc-=.055}}draw();requestAnimationFrame(loop)}
function tick(dt){t+=dt;if(t>=dur)return finish();events();teams.forEach(a=>{a.credit+=19*(a.territory<N*.12?1.15:1)*dt;while(a.credit>=1){act(a);a.credit--}});stats();teams.forEach(a=>a.score+=dt*(a.territory*.045+a.resources*1.5));if(((t*5)|0)!==(((t-dt)*5)|0))ui()}
function events(){let p=t/dur;if(p>=.33&&!flags.has('p')){flags.add('p');resources(12,true);banner('资源潮汐：中央新增高价值节点');log('资源潮汐出现，中央区域价值上升。')}if(p>=.62&&!flags.has('o')){flags.add('o');for(let y=25;y<39;y++)for(let x=25;x<39;x++){let i=I(x,y);if(!res[i]&&Math.random()<.09)res[i]=3}banner('核心节点上线：中央资源价值暴涨');log('核心节点上线，中央战区进入决胜阶段。')}if(p>=.82&&!flags.has('f')){flags.add('f');banner('终局超频：全体扩张效率提升');log('终局超频开始，最后冲刺。')}}
function banner(s){el.banner.textContent=s;el.banner.classList.add('show');clearTimeout(flash);flash=setTimeout(()=>el.banner.classList.remove('show'),2400)}
function act(a){let o=opts(a.id);if(!o.length)return reclaim(a);let m;if(a.strategy==='bfs')m=best(o,z=>neighbors(z.to,a.id)*2+res[z.to]*5-ter[z.to]*1.2+Math.random()*2);else if(a.strategy==='dfs')m=best(o,z=>(z.dir[0]===a.lastDir[0]&&z.dir[1]===a.lastDir[1]?8:0)+(own[z.to]>=0?3.5:0)+res[z.to]*2-ter[z.to]+Math.random()*3.5);else if(a.strategy==='astar'){if(!a.target||!res[I(a.target[0],a.target[1])])a.target=target(a.id);m=a.target?best(o,z=>-MD(XY(z.to),a.target)*1.9-ter[z.to]*1.8+res[z.to]*9+neighbors(z.to,a.id)*.8+Math.random()*1.3):greedy(o)}else if(a.strategy==='greedy')m=greedy(o);else m=o[RI(o.length)];if(m)claim(a,m)}
function opts(id){let owned=[],out=[];for(let i=0;i<N;i++)if(own[i]===id)owned.push(i);if(!owned.length)return out;let st=owned.length>250?Math.ceil(owned.length/250):1,begin=RI(Math.min(st,owned.length));for(let n=begin;n<owned.length;n+=st){let from=owned[n],[x,y]=XY(from);for(let d of D){let nx=x+d[0],ny=y+d[1];if(!IB(nx,ny))continue;let to=I(nx,ny);if(own[to]===id||core[to]>=0)continue;out.push({from,to,dir:d})}}return out}
function best(o,f){let b=null,s=-1e9;o.forEach(z=>{let q=f(z);if(q>s){s=q;b=z}});return b}
function greedy(o){return best(o,z=>res[z.to]*13+(own[z.to]>=0?7:0)+(own[z.to]>=0?Math.max(0,3-neighbors(z.to,own[z.to]))*2.2:0)-ter[z.to]*1.4+Math.random()*2.5)}
function target(id){let b=null,s=-1e9;for(let i=0;i<N;i++){if(!res[i]||own[i]===id)continue;let p=XY(i),q=res[i]*18-MD(CP[id],p)*.28+Math.random()*5;if(q>s){s=q;b=p}}return b}
function claim(a,m){let v=own[m.to],fs=neighbors(m.to,a.id),vs=v>=0?neighbors(m.to,v):0,ch=v<0?.93-(ter[m.to]-1)*.12:.40+fs*.105-vs*.075-(ter[m.to]-1)*.05;if(a.strategy==='greedy')ch+=.04;if(a.strategy==='dfs'&&m.dir[0]===a.lastDir[0]&&m.dir[1]===a.lastDir[1])ch+=.055;if(flags.has('f'))ch+=.07;ch=CL(ch,.12,.92);if(Math.random()<=ch){if(v>=0&&v!==a.id){a.captures++;a.score+=2.2+res[m.to]*3}else a.score+=.15;own[m.to]=a.id;a.lastDir=m.dir;if(res[m.to])a.score+=res[m.to]*8}}
function reclaim(a){let[cx,cy]=CP[a.id];for(let r=2;r<8;r++){let q=[];for(let y=cy-r;y<=cy+r;y++)for(let x=cx-r;x<=cx+r;x++)if(IB(x,y)){let i=I(x,y);if(core[i]<0&&own[i]!==a.id)q.push(i)}if(q.length){own[q[RI(q.length)]]=a.id;return}}}
function neighbors(i,id){let[x,y]=XY(i),n=0;for(let d of D){let nx=x+d[0],ny=y+d[1];if(IB(nx,ny)&&own[I(nx,ny)]===id)n++}return n}
function stats(){let a=[0,0,0,0],r=[0,0,0,0];for(let i=0;i<N;i++){let v=own[i];if(v>=0){a[v]++;if(res[i])r[v]+=res[i]}}teams.forEach(x=>{x.territory=a[x.id];x.resources=r[x.id]})}
function ui(){el.timer.textContent=ft(dur-t);let a=[...teams].sort((x,y)=>y.score-x.score),m=Math.max(1,...a.map(x=>x.score));el.score.innerHTML=a.map((x,k)=>'<div class="score-row"><div class="score-top"><div class="score-name"><span>'+(k+1)+'</span><i class="team-swatch" style="background:'+COL[x.id]+'"></i>'+S[x.strategy][0]+'</div><div class="score-number">'+Math.round(x.score)+'</div></div><div class="bar"><i style="width:'+(x.score/m*100)+'%;background:'+COL[x.id]+'"></i></div><div class="score-meta"><span>领地 '+(x.territory/N*100).toFixed(1)+'%</span><span>资源 '+x.resources+'</span><span>翻色 '+x.captures+'</span></div></div>').join('')}
function log(s){let d=document.createElement('div');d.className='feed-item';d.innerHTML='<span class="feed-time">'+ft(t)+'</span>'+s;el.feed.prepend(d);while(el.feed.children.length>30)el.feed.lastChild.remove()}
function finish(){run=false;end=true;t=dur;stats();ui();state('已结算');el.pause.disabled=true;el.start.disabled=false;el.start.textContent='新一局';let a=[...teams].sort((x,y)=>y.score-x.score),w=a[0];el.title.textContent=TN[w.id]+'获胜 · '+S[w.strategy][0];el.sum.textContent='最终 '+Math.round(w.score)+' 分，控制 '+(w.territory/N*100).toFixed(1)+'% 的战场。';el.list.innerHTML=a.map((x,k)=>'<div class="result-line"><span>'+(k+1)+'. '+TN[x.id]+' · '+S[x.strategy][0]+'</span><strong>'+Math.round(x.score)+' 分</strong></div>').join('');log(S[w.strategy][0]+' 以 '+Math.round(w.score)+' 分拿下本局。');el.dlg.showModal()}
function draw(){let cw=C.width/W,ch=C.height/H;X.clearRect(0,0,C.width,C.height);for(let y=0;y<H;y++)for(let x=0;x<W;x++){let i=I(x,y),v=own[i];if(v>=0){X.fillStyle=COL[v];X.globalAlpha=ter[i]===3?.72:ter[i]===2?.84:.96}else{X.fillStyle=ter[i]===3?'#c8ced8':ter[i]===2?'#dde2e9':'#f3f5f8';X.globalAlpha=1}X.fillRect(x*cw,y*ch,cw+.4,ch+.4);if(res[i]){X.globalAlpha=1;X.fillStyle=res[i]===3?'#ffb703':'#ffd166';X.beginPath();X.arc(x*cw+cw/2,y*ch+ch/2,res[i]===3?cw*.27:cw*.18,0,Math.PI*2);X.fill()}if(core[i]>=0){X.globalAlpha=1;X.strokeStyle='#fff';X.lineWidth=Math.max(1,cw*.18);X.strokeRect(x*cw+cw*.18,y*ch+ch*.18,cw*.64,ch*.64)}}X.globalAlpha=1}
el.start.onclick=start;el.pause.onclick=pause;el.reset.onclick=reset;el.dur.onchange=()=>{if(!run)reset()};el.again.onclick=()=>{el.dlg.close();reset();start()};el.close.onclick=()=>el.dlg.close();config();reset();requestAnimationFrame(loop);
